import sources from "./assets/wikipedia/ai-sources.json" with { type: "json" };

const articleById = new Map(
  sources.articles.map((article) => [article.id, article]),
);
const passageById = new Map(
  sources.passages.map((passage) => [passage.id, passage]),
);

const questionSpecs = [
  {
    id: "dad-ai-001",
    topic: "ai",
    passageId: "ai-definition",
    prompt:
      "What capability is at the center of the passage’s definition of artificial intelligence?",
    options: [
      "Computational systems performing tasks associated with human intelligence.",
      "A catalog of applications limited to search engines and chatbots.",
      "A research field concerned only with mathematical optimization and formal logic.",
      "A system’s ability to perform one preprogrammed physical routine.",
    ],
    answer: 0,
    explanation:
      "지문은 AI를 학습·추론·문제 해결처럼 인간 지능과 관련된 일을 수행하는 계산 시스템의 능력으로 정의합니다.",
    difficulty: 1,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-002",
    topic: "ai",
    passageId: "ai-definition",
    prompt:
      "Why do AI researchers develop methods that let machines perceive their environment?",
    options: [
      "To make actions independent of any defined objective.",
      "To let machines take actions that maximize their chances of achieving defined goals.",
      "To let machines perceive environments without that perception affecting decisions.",
      "To maximize available data rather than the chances of reaching a goal.",
    ],
    answer: 1,
    explanation:
      "환경을 지각하게 하는 방법은 정의된 목표를 달성할 가능성을 높이는 행동으로 이어지기 때문입니다.",
    difficulty: 2,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-003",
    topic: "ai",
    passageId: "ai-definition",
    prompt:
      "Which pair of activities is explicitly included among the traditional goals of AI research?",
    options: [
      "Image editing and database administration.",
      "Hardware manufacturing and network maintenance.",
      "Knowledge representation and natural language processing.",
      "Autonomous driving and video compression.",
    ],
    answer: 2,
    explanation:
      "전통적 목표 목록에 지식 표현과 자연어 처리가 함께 제시됩니다.",
    difficulty: 1,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-004",
    topic: "ai",
    passageId: "ai-definition",
    prompt:
      "In context, what does “maximise their chances” most nearly indicate about machine actions?",
    options: [
      "Actions are selected to reduce the need for a defined objective.",
      "Actions are judged only by how humanlike their appearance is.",
      "Actions are chosen to maximize speed regardless of the defined goal.",
      "They are selected to improve the likelihood of reaching a defined goal.",
    ],
    answer: 3,
    explanation:
      "지문에서 그 표현은 정의된 목표를 이룰 가능성을 높이는 방향으로 행동한다는 뜻입니다.",
    difficulty: 3,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-005",
    topic: "ai",
    passageId: "ai-history",
    prompt:
      "When does the passage say artificial intelligence was founded as an academic discipline?",
    options: [
      "1956.",
      "1950, when Turing introduced the imitation game.",
      "1984, when the term AI winter first appeared.",
      "2017, when transformer-based growth accelerated.",
    ],
    answer: 0,
    explanation:
      "지문은 AI가 학문 분야로 설립된 시점을 1956년이라고 명시합니다.",
    difficulty: 1,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-006",
    topic: "ai",
    passageId: "ai-history",
    prompt:
      "What development is linked to the substantial rise in funding and interest after 2012?",
    options: [
      "GPU use accelerated neural networks, but deep learning did not outperform earlier techniques.",
      "Using GPUs to accelerate neural networks while deep learning outperformed earlier techniques.",
      "Funding declined after GPUs replaced neural networks with generative AI.",
      "The transformer architecture alone caused the rise after 2012.",
    ],
    answer: 1,
    explanation:
      "2012년 이후 GPU로 신경망을 가속하고 딥러닝이 이전 기법을 능가한 일이 자금과 관심 증가와 연결됩니다.",
    difficulty: 2,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-007",
    topic: "ai",
    passageId: "ai-history",
    prompt:
      "According to the passage, what accelerated AI growth further after 2017?",
    options: [
      "The stronger performance of deep learning after 2012.",
      "The founding of AI as an academic discipline in 1956.",
      "The transformer architecture.",
      "The spread of generative AI during the 2020s.",
    ],
    answer: 2,
    explanation:
      "지문은 2017년 이후 성장 가속의 요인으로 transformer architecture를 듭니다.",
    difficulty: 1,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-008",
    topic: "ai",
    passageId: "ai-history",
    prompt:
      "Which concern is presented alongside AI safety and unintended harms?",
    options: [
      "Only technical reliability and performance concerns.",
      "Only long-term economic effects on companies.",
      "Only environmental effects, without ethical concerns.",
      "Ethical, long-term, environmental, and potential existential effects.",
    ],
    answer: 3,
    explanation:
      "마지막 문장은 안전·의도치 않은 피해와 함께 윤리적·장기적·환경적 영향 및 잠재적 실존 위험을 열거합니다.",
    difficulty: 3,
    source: {
      title: "Artificial intelligence",
      url: "https://en.wikipedia.org/wiki/Artificial_intelligence",
      revisionId: 1376681180,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376681180",
      revisionTimestamp: "2026-09-25T16:57:30Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-009",
    topic: "ai",
    passageId: "ml-foundations",
    prompt:
      "What makes the algorithms described as machine learning in this passage distinctive?",
    options: [
      "They learn from data and generalize to unseen data without being explicitly programmed for each task.",
      "They learn only from seen data and require explicit programming for every unseen case.",
      "They infer rules from data but cannot generalize beyond the training examples.",
      "They are statistical algorithms explicitly programmed for each individual task.",
    ],
    answer: 0,
    explanation:
      "머신러닝 알고리즘은 데이터에서 배우고 보지 못한 데이터로 일반화하며 명시적으로 일일이 프로그래밍되지 않는다는 점이 핵심입니다.",
    difficulty: 2,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-010",
    topic: "ai",
    passageId: "ml-foundations",
    prompt:
      "Which two methods does the passage identify as foundations of machine learning?",
    options: [
      "Statistics and formal logic.",
      "Statistics and mathematical optimisation.",
      "Mathematical optimisation and natural language processing.",
      "Data mining and unsupervised learning.",
    ],
    answer: 1,
    explanation:
      "지문은 통계와 수학적 최적화 방법을 머신러닝의 기초라고 합니다.",
    difficulty: 1,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-011",
    topic: "ai",
    passageId: "ml-foundations",
    prompt: "What does data mining focus on in the passage?",
    options: [
      "Exploratory data analysis through supervised learning.",
      "Predictive modeling from labeled examples rather than exploratory analysis.",
      "Exploratory data analysis through unsupervised learning.",
      "Rule-based diagnosis through expert systems.",
    ],
    answer: 2,
    explanation:
      "데이터 마이닝은 비지도 학습을 통한 탐색적 데이터 분석에 초점을 둔다고 설명됩니다.",
    difficulty: 1,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-012",
    topic: "ai",
    passageId: "ml-foundations",
    prompt:
      "How does probably approximately correct learning function in the described theory?",
    options: [
      "A framework for assessing the visual quality of images.",
      "A statistical method that replaces empirical risk minimisation.",
      "A rule that permits generalization only to data already seen.",
      "As a mathematical and statistical framework for describing machine learning.",
    ],
    answer: 3,
    explanation:
      "지문은 probably approximately correct learning을 머신러닝을 기술하는 수학·통계적 틀로 위치시킵니다.",
    difficulty: 3,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-013",
    topic: "ai",
    passageId: "ml-deep",
    prompt:
      "What change allowed neural networks to surpass many previous machine-learning approaches?",
    options: [
      "Advances in deep learning.",
      "The expansion of data mining without changes to neural networks.",
      "The return of expert systems developed in the 1980s.",
      "The increasingly interchangeable use of the terms AI and ML.",
    ],
    answer: 0,
    explanation:
      "딥러닝 분야의 발전이 신경망을 많은 기존 접근법보다 높은 성능으로 이끌었다고 지문이 말합니다.",
    difficulty: 2,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-014",
    topic: "ai",
    passageId: "ml-deep",
    prompt:
      "From which period does the passage date machine learning’s dominance within AI?",
    options: [
      "The founding of AI as an academic discipline in the 1950s.",
      "The late 2000s and early 2010s onward.",
      "The major AI winter from 1974 to 1980.",
      "The period of generative-AI growth in the 2020s only.",
    ],
    answer: 1,
    explanation:
      "머신러닝의 AI 내 지배력은 2000년대 후반과 2010년대 초반부터라고 제시됩니다.",
    difficulty: 2,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-015",
    topic: "ai",
    passageId: "ml-deep",
    prompt:
      "What relationship between the terms “machine learning” and “artificial intelligence” does the passage emphasize?",
    options: [
      "They are exact synonyms and are never used interchangeably.",
      "They describe separate levels of the same field and are never compared.",
      "They are often used interchangeably even though they are not synonymous.",
      "One term has replaced the other in every current AI context.",
    ],
    answer: 2,
    explanation:
      "두 용어가 서로 바꿔 쓰이기도 하지만 동의어는 아니라고 명시합니다.",
    difficulty: 2,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-016",
    topic: "ai",
    passageId: "ml-deep",
    prompt: "Which contrast is supported by the passage?",
    options: [
      "Machine learning is separate from AI, although the two terms are interchangeable.",
      "AI is a field within machine learning, and the terms are synonymous.",
      "Machine learning covers only traditional methods, while AI covers only deep learning.",
      "Machine learning is a field within AI, but the terms are not synonymous.",
    ],
    answer: 3,
    explanation:
      "머신러닝은 AI 안의 연구 분야로 소개되지만 두 용어의 의미가 같지는 않습니다.",
    difficulty: 3,
    source: {
      title: "Machine learning",
      url: "https://en.wikipedia.org/wiki/Machine_learning",
      revisionId: 1376251196,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376251196",
      revisionTimestamp: "2026-09-23T01:33:14Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-017",
    topic: "ai",
    passageId: "dl-basics",
    prompt: "What does the adjective “deep” refer to in deep learning?",
    options: [
      "The use of multiple layers in a neural network.",
      "The number of training examples rather than the network structure.",
      "A neural network’s ability to reproduce an organism’s brain function.",
      "Using one input layer with no additional layers.",
    ],
    answer: 0,
    explanation:
      "딥(deep)은 네트워크에서 여러 층을 사용하는 것을 가리킨다고 지문이 설명합니다.",
    difficulty: 1,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-018",
    topic: "ai",
    passageId: "dl-basics",
    prompt:
      "Which training arrangements are listed as possible methods for deep learning?",
    options: [
      "Supervised, semi-supervised, and rule-based.",
      "Supervised, semi-supervised, and unsupervised.",
      "Supervised and unsupervised, but not semi-supervised.",
      "Semi-supervised and unsupervised, but not supervised.",
    ],
    answer: 1,
    explanation:
      "지문은 지도·반지도·비지도 방법을 모두 딥러닝 방식으로 열거합니다.",
    difficulty: 1,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-019",
    topic: "ai",
    passageId: "dl-basics",
    prompt:
      "What inspiration and process are connected in the passage’s description of deep learning?",
    options: [
      "Biological neuroscience and manually writing each response.",
      "Mathematical optimisation and stacking physical processors.",
      "Biological neuroscience and training stacked artificial neurons to process data.",
      "Computer vision and training only output labels without artificial neurons.",
    ],
    answer: 2,
    explanation:
      "생물학적 신경과학에서 영감을 받고 층층이 쌓은 인공 뉴런을 훈련한다고 설명합니다.",
    difficulty: 2,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-020",
    topic: "ai",
    passageId: "dl-basics",
    prompt:
      "Which set of tasks appears in the first sentence as examples of what deep learning performs?",
    options: [
      "Classification, regression, and machine translation.",
      "Representation learning, planning, and perception.",
      "Classification, optimisation, and neural-architecture design.",
      "Classification, regression, and representation learning.",
    ],
    answer: 3,
    explanation:
      "첫 문장의 예시는 classification, regression, representation learning입니다.",
    difficulty: 1,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-021",
    topic: "ai",
    passageId: "dl-uses",
    prompt: "Which item is named as a deep-learning network architecture?",
    options: [
      "Convolutional neural networks.",
      "Statistical optimisation methods.",
      "Representation learning as a task rather than an architecture.",
      "Medical image analysis as an application area.",
    ],
    answer: 0,
    explanation:
      "지문이 열거한 네트워크 구조 중 convolutional neural networks가 포함됩니다.",
    difficulty: 1,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-022",
    topic: "ai",
    passageId: "dl-uses",
    prompt:
      "Which pair of application areas is explicitly included in the passage?",
    options: [
      "Database administration and operating-system design.",
      "Computer vision and speech recognition.",
      "Rule-based diagnosis and compiler optimisation.",
      "Robotics control and financial forecasting.",
    ],
    answer: 1,
    explanation:
      "적용 분야 목록에는 computer vision과 speech recognition이 함께 나옵니다.",
    difficulty: 1,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-023",
    topic: "ai",
    passageId: "dl-uses",
    prompt:
      "How does the passage qualify deep learning's performance relative to human experts?",
    options: [
      "It exceeds every human expert in every listed application.",
      "It remains below human experts across all listed applications.",
      "Its results can match human experts and sometimes surpass them.",
      "Its performance is assessed only as a model of the human brain.",
    ],
    answer: 2,
    explanation:
      "지문은 여러 응용 분야에서 인간 전문가와 비교할 만한 결과를 내며, 일부 경우에는 이를 능가한다고 한정합니다. 모든 분야에서 항상 우월하다는 주장은 아닙니다.",
    difficulty: 3,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-024",
    topic: "ai",
    passageId: "dl-uses",
    prompt:
      "What influenced the early forms of neural networks described in the passage?",
    options: [
      "Early networks reproduced every operation of a human brain exactly.",
      "Biological inspiration began only after the listed applications succeeded.",
      "Early networks were inspired exclusively by machine-translation programs.",
      "Early networks drew inspiration from biological information processing and communication.",
    ],
    answer: 3,
    explanation:
      "마지막 문장은 초기 신경망이 생물학적 정보 처리와 분산 통신 구조, 특히 인간의 뇌에서 영감을 얻었다고 설명합니다.",
    difficulty: 3,
    source: {
      title: "Deep learning",
      url: "https://en.wikipedia.org/wiki/Deep_learning",
      revisionId: 1373512453,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1373512453",
      revisionTimestamp: "2026-09-06T11:22:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-025",
    topic: "ai",
    passageId: "alphago-evolution",
    prompt: "Who developed AlphaGo according to the passage?",
    options: [
      "London-based DeepMind Technologies.",
      "Google’s search-engine division independently of DeepMind Technologies.",
      "The research group that later created MuZero, rather than DeepMind Technologies.",
      "The Korea Baduk Association’s professional division.",
    ],
    answer: 0,
    explanation:
      "AlphaGo는 런던 기반 DeepMind Technologies가 개발했다고 지문에 나옵니다.",
    difficulty: 1,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-026",
    topic: "ai",
    passageId: "alphago-evolution",
    prompt: "What happened to AlphaGo Master after its competitive period?",
    options: [
      "It continued competing under the name Master until it was replaced by AlphaZero.",
      "It was succeeded by the self-taught AlphaGo Zero.",
      "It was retired and immediately replaced by MuZero.",
      "It learned only from human games before becoming AlphaZero.",
    ],
    answer: 1,
    explanation:
      "경쟁 플레이 후 Master는 인간 기보 없이 스스로 학습한 AlphaGo Zero로 이어졌습니다.",
    difficulty: 2,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-027",
    topic: "ai",
    passageId: "alphago-evolution",
    prompt: "Which additional games did AlphaZero play, as stated here?",
    options: [
      "Chess and Go only.",
      "Shogi and poker.",
      "Chess and shogi.",
      "Go and shogi only.",
    ],
    answer: 2,
    explanation:
      "AlphaZero는 Go 외에 chess와 shogi도 플레이했다고 지문이 말합니다.",
    difficulty: 1,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-028",
    topic: "ai",
    passageId: "alphago-evolution",
    prompt: "What distinguishes MuZero in the sequence described?",
    options: [
      "MuZero learns the rules from human teachers after AlphaZero.",
      "MuZero is limited to Go and chess.",
      "MuZero uses human games to learn the rules it is given.",
      "It learns without being taught the rules.",
    ],
    answer: 3,
    explanation:
      "MuZero의 특징은 규칙을 배우도록 가르치지 않아도 학습한다는 점입니다.",
    difficulty: 2,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-029",
    topic: "ai",
    passageId: "alphago-matches",
    prompt:
      "How did AlphaGo's fourth-game loss relate to the outcome of the Lee Sedol match?",
    options: [
      "It lost that game but still won the five-game match by four games to one.",
      "The loss ended the match before a fifth game could be played.",
      "The loss gave Lee Sedol an overall three-games-to-two victory.",
      "It received the honorary rank despite losing four of the five games.",
    ],
    answer: 0,
    explanation:
      "알파고는 네 번째 대국에서는 졌지만 이세돌이 마지막 대국에서 기권하면서 전체 경기는 알파고의 4 대 1 승리로 끝났습니다. 한 대국의 패배와 전체 결과를 구분해야 합니다.",
    difficulty: 3,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-030",
    topic: "ai",
    passageId: "alphago-matches",
    prompt:
      "How does the passage distinguish the professional milestones reached in 2015 and 2016?",
    options: [
      "The earlier match involved an amateur, while the later match used a handicap.",
      "The earlier milestone concerned a human professional; the later one specifically concerned a 9-dan professional.",
      "The earlier milestone required a handicap, while the later one used a smaller board.",
      "The earlier opponent was Lee Sedol, while Fan Hui was the opponent in the later milestone.",
    ],
    answer: 1,
    explanation:
      "2015년에는 판후이를 상대로 접바둑 없이 인간 프로 기사를 처음 이겼고, 2016년에는 같은 조건에서 9단 프로 기사를 처음 이긴 기록으로 설명됩니다.",
    difficulty: 1,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-031",
    topic: "ai",
    passageId: "alphago-matches",
    prompt: "What milestone did the original AlphaGo reach in October 2015?",
    options: [
      "It beat a human professional with a handicap on a full-sized board.",
      "It became the first computer to beat a 9-dan professional in March 2016.",
      "It beat a human professional Go player without handicap on a full-sized board.",
      "It beat the world’s top-ranked player at the 2017 Future of Go Summit.",
    ],
    answer: 2,
    explanation:
      "2015년 10월 원래 AlphaGo는 19×19판에서 핸디캡 없이 인간 프로를 이긴 첫 컴퓨터 Go 프로그램이 됐습니다.",
    difficulty: 2,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-032",
    topic: "ai",
    passageId: "alphago-matches",
    prompt: "Which result followed AlphaGo’s five-game match with Lee Sedol?",
    options: [
      "Lee won 4–1, and AlphaGo received an honorary 9-dan.",
      "AlphaGo won 4–1 but received a professional 9-dan from the Chinese Weiqi Association.",
      "AlphaGo lost the fourth game and therefore finished 1–4 without recognition.",
      "AlphaGo finished with a 4–1 score, and it received an honorary 9-dan from the Korea Baduk Association.",
    ],
    answer: 3,
    explanation:
      "Lee와의 경기에서 최종 결과는 AlphaGo의 4 대 1 승리였고, 이후 한국기원이 명예 9단을 수여했습니다.",
    difficulty: 3,
    source: {
      title: "AlphaGo",
      url: "https://en.wikipedia.org/wiki/AlphaGo",
      revisionId: 1371513984,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1371513984",
      revisionTimestamp: "2026-08-26T22:35:31Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-033",
    topic: "ai",
    passageId: "eliza-design",
    prompt: "When and where was ELIZA developed, and by whom?",
    options: [
      "From 1964 to 1967 at MIT by Joseph Weizenbaum.",
      "From 1964 to 1967 at the University of Manchester by Joseph Weizenbaum.",
      "From 1964 to 1967 at MIT by Alan Turing.",
      "From 1967 to 1970 at MIT by Joseph Weizenbaum.",
    ],
    answer: 0,
    explanation:
      "지문 첫 문장은 1964~1967년 MIT에서 Joseph Weizenbaum이 개발했다고 명시합니다.",
    difficulty: 1,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-034",
    topic: "ai",
    passageId: "eliza-design",
    prompt: "How did ELIZA create an illusion of understanding?",
    options: [
      "By using pattern matching without substitution.",
      "By using pattern matching and substitution.",
      "By scripting responses based on understanding each user’s meaning.",
      "By offering direct advice instead of reflecting users' statements.",
    ],
    answer: 1,
    explanation:
      "패턴 매칭과 치환 방법이 사용자의 이해 착각을 만들었다고 설명됩니다.",
    difficulty: 1,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-035",
    topic: "ai",
    passageId: "eliza-design",
    prompt: "What did the DOCTOR script simulate?",
    options: [
      "A Rogerian psychotherapist who gives direct advice rather than reflecting patients’ words.",
      "A Rogerian psychologist who classifies patient symptoms with if–then rules.",
      "A Rogerian psychotherapist who often reflects patients’ words.",
      "A general conversation partner with no psychotherapeutic role.",
    ],
    answer: 2,
    explanation:
      "DOCTOR는 환자의 말을 되비추는 Rogerian 학파 심리치료사를 모사했습니다.",
    difficulty: 2,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-036",
    topic: "ai",
    passageId: "eliza-design",
    prompt:
      "What caution follows from the passage's description of ELIZA's conversations?",
    options: [
      "Separating scripts from the main program established genuine understanding.",
      "Using MAD-SLIP prevented users from finding its responses convincing.",
      "The DOCTOR script established that the program could reliably diagnose patients.",
      "A convincing impression of understanding did not mean the program really understood the conversation.",
    ],
    answer: 3,
    explanation:
      "지문은 패턴 대응과 치환으로 이해하는 듯한 인상을 주었지만 실제로 대화 내용을 이해한다고 볼 응답은 없었다고 말합니다. 사용자에게 주는 인상과 실제 이해를 구분해야 합니다.",
    difficulty: 2,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-037",
    topic: "ai",
    passageId: "eliza-reception",
    prompt: "What was Weizenbaum’s original intention for ELIZA?",
    options: [
      "To explore communication between humans and machines.",
      "To demonstrate genuine machine understanding to users.",
      "To treat psychological issues directly rather than study communication.",
      "To compare human and machine conversation for a formal test only.",
    ],
    answer: 0,
    explanation:
      "Weizenbaum은 인간과 기계 사이의 소통을 탐구하려고 ELIZA를 만들었습니다.",
    difficulty: 1,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-038",
    topic: "ai",
    passageId: "eliza-reception",
    prompt: "What does the term “ELIZA effect” refer to in the passage?",
    options: [
      "Users attributing machine-like limitations to the program.",
      "People attributing human-like feelings to the program.",
      "Academics evaluating the program’s benchmark results.",
      "The discovery of the pattern-matching source code in 2021.",
    ],
    answer: 1,
    explanation:
      "ELIZA effect는 사람들이 프로그램에 인간 같은 감정을 부여한 현상입니다.",
    difficulty: 2,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-039",
    topic: "ai",
    passageId: "eliza-reception",
    prompt:
      "Which contrast does the passage draw between expectations and ELIZA’s actual ability?",
    options: [
      "Some academics expected helpful influence, and ELIZA had true understanding.",
      "No one expected influence, but users recognized ELIZA’s limitations.",
      "Some academics expected helpful influence, but ELIZA could not converse with true understanding.",
      "Academics expected no influence, while users denied that ELIZA seemed intelligent.",
    ],
    answer: 2,
    explanation:
      "일부 학자들은 도움을 기대했지만 지문은 ELIZA가 진정한 이해로 대화할 수 없었다고 대비합니다.",
    difficulty: 3,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-040",
    topic: "ai",
    passageId: "eliza-reception",
    prompt: "What happened despite Weizenbaum’s insistence to the contrary?",
    options: [
      "Many early users questioned ELIZA but understood its limitations.",
      "Weizenbaum attributed human-like feelings to ELIZA, but users did not.",
      "Users accepted ELIZA’s intelligence only after its source code was found in 2021.",
      "Many early users were convinced of ELIZA’s intelligence and understanding.",
    ],
    answer: 3,
    explanation:
      "Weizenbaum의 반대 주장에도 많은 초기 사용자가 ELIZA를 지능적이고 이해한다고 믿었습니다.",
    difficulty: 2,
    source: {
      title: "ELIZA",
      url: "https://en.wikipedia.org/wiki/ELIZA",
      revisionId: 1374884270,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374884270",
      revisionTimestamp: "2026-09-14T16:52:56Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-041",
    topic: "ai",
    passageId: "turing-mechanics",
    prompt:
      "In the modern version of the Turing test, what does a human evaluator judge?",
    options: [
      "A text transcript of a natural-language conversation between a human and a machine.",
      "A text transcript of a natural-language conversation between two machines.",
      "Whether the machine’s responses are factually correct in a written examination.",
      "A nonverbal robotic performance without an interactive transcript.",
    ],
    answer: 0,
    explanation:
      "현대판에서는 평가자가 인간과 기계의 자연어 대화 텍스트 기록을 판단합니다.",
    difficulty: 1,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-042",
    topic: "ai",
    passageId: "turing-mechanics",
    prompt: "When does the machine pass according to the passage?",
    options: [
      "When it answers every question correctly.",
      "When the evaluator cannot reliably tell it apart from the human.",
      "When the evaluator identifies the machine from the transcript’s length.",
      "When it imitates a human even though the evaluator reliably distinguishes it.",
    ],
    answer: 1,
    explanation:
      "평가자가 인간과 기계를 신뢰성 있게 구별하지 못하면 통과합니다.",
    difficulty: 1,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-043",
    topic: "ai",
    passageId: "turing-mechanics",
    prompt: "What do the results not depend on in this description?",
    options: [
      "The machine’s ability to imitate human answers.",
      "Whether the transcript uses natural-language conversation.",
      "The machine’s ability to answer questions correctly.",
      "The evaluator’s ability to identify the machine reliably.",
    ],
    answer: 2,
    explanation:
      "지문은 결과가 질문에 정확히 답하는 능력에는 의존하지 않고 인간과 얼마나 비슷한지가 중요하다고 합니다.",
    difficulty: 2,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-044",
    topic: "ai",
    passageId: "turing-mechanics",
    prompt:
      "Which evaluation procedure would conflict with the Turing test described in the passage?",
    options: [
      "A human evaluator examines a written record of human-machine dialogue.",
      "The evaluator tries to determine which participant is the machine.",
      "The machine passes when its responses cannot reliably be distinguished from a human's.",
      "The machine is judged solely by factual accuracy, regardless of whether its responses resemble a human's.",
    ],
    answer: 3,
    explanation:
      "지문은 답의 정확성보다 인간의 답과 얼마나 닮았는지를 평가한다고 명시합니다. 따라서 인간다운 응답인지 무시하고 사실 정확성만으로 판정하는 절차는 이 설명과 맞지 않습니다.",
    difficulty: 3,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-045",
    topic: "ai",
    passageId: "turing-origins",
    prompt: "When and under what title did Turing introduce the test?",
    options: [
      "In 1950 as the imitation game in “Computing Machinery and Intelligence.”",
      "In 1950 as “Can machines think?” in a paper about AI winters.",
      "In 1964 as the imitation game at MIT.",
      "In 1950 as a neural-network benchmark at the University of Manchester.",
    ],
    answer: 0,
    explanation:
      "Turing은 1950년 논문에서 imitation game으로 시험을 소개했습니다.",
    difficulty: 1,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-046",
    topic: "ai",
    passageId: "turing-origins",
    prompt: "Why did Turing replace the question “Can machines think?”?",
    options: [
      "Because Turing thought “thinking” was easy to define.",
      "Because “thinking” was difficult to define and another formulation was more unambiguous.",
      "Because the imitation game excluded an interrogator.",
      "Because a human evaluator could guarantee that every answer was correct.",
    ],
    answer: 1,
    explanation:
      "“thinking”의 정의가 어렵기 때문에 더 명확한 표현으로 질문을 바꿨다고 지문이 말합니다.",
    difficulty: 2,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-047",
    topic: "ai",
    passageId: "turing-origins",
    prompt: "What happens in the three-person imitation game described?",
    options: [
      "An interrogator asks questions of two machines in another room to judge their intelligence.",
      "A man and a woman answer questions, but the interrogator determines their intelligence rather than their sex.",
      "An interrogator asks questions of a man and a woman in another room to determine their sex.",
      "An interrogator asks only a machine questions in an open room.",
    ],
    answer: 2,
    explanation:
      "심문자가 다른 방의 남자와 여자에게 질문해 두 참가자의 성별을 판단하는 게임입니다.",
    difficulty: 2,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-048",
    topic: "ai",
    passageId: "turing-origins",
    prompt:
      "What did Turing argue in the remainder of the paper, according to the passage?",
    options: [
      "He accepted the major objections and withdrew the proposition.",
      "He argued against whether computers could play Go.",
      "He defined consciousness as a form of machine performance.",
      "He argued against the major objections to the proposition that machines can think.",
    ],
    answer: 3,
    explanation:
      "지문의 마지막 문장은 Turing이 기계가 생각할 수 있다는 주장에 대한 주요 반론에 맞섰다고 설명합니다.",
    difficulty: 3,
    source: {
      title: "Turing test",
      url: "https://en.wikipedia.org/wiki/Turing_test",
      revisionId: 1374125371,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374125371",
      revisionTimestamp: "2026-09-10T00:38:29Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-049",
    topic: "ai",
    passageId: "winter-definition",
    prompt: "What is an AI winter?",
    options: [
      "A period of reduced funding and interest in AI research.",
      "A period of reduced funding but increased interest in AI research.",
      "A period of disappointment followed immediately by renewed funding.",
      "A period when only academic AI research continues while industry withdraws.",
    ],
    answer: 0,
    explanation: "AI winter는 AI 연구의 자금과 관심이 줄어드는 기간입니다.",
    difficulty: 1,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-050",
    topic: "ai",
    passageId: "winter-definition",
    prompt:
      "When and where did the term first appear according to the passage?",
    options: [
      "In 1984 at an AAAI annual meeting’s technical demonstration.",
      "In 1984 at an AAAI annual-meeting public debate.",
      "In 1974–1980 during a debate about the first AI winter.",
      "In 1984 in a business-press article rather than a public debate.",
    ],
    answer: 1,
    explanation:
      "용어는 1984년 당시 AAAI의 연례 회의에서 열린 공개 토론에서 처음 등장했습니다.",
    difficulty: 2,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-051",
    topic: "ai",
    passageId: "winter-definition",
    prompt:
      "Which sequence matches the chain reaction warned about by Schank and Minsky?",
    options: [
      "Community optimism is followed by press optimism, funding growth, and the end of serious research.",
      "Press pessimism comes before community pessimism, followed by renewed funding.",
      "Community pessimism is followed by press pessimism, funding cuts, and the end of serious research.",
      "Community pessimism is followed by renewed funding and expanded serious research.",
    ],
    answer: 2,
    explanation:
      "두 연구자는 공동체의 비관에서 언론의 비관, 자금 삭감, 진지한 연구의 종결로 이어지는 순서를 설명했습니다.",
    difficulty: 3,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-052",
    topic: "ai",
    passageId: "winter-definition",
    prompt:
      "Why did Schank and Minsky warn the business community at the 1984 debate?",
    options: [
      "They argued that earlier funding cuts guaranteed permanent financial stability.",
      "They believed that press pessimism would prevent researchers from becoming disappointed.",
      "They announced that serious AI research had already permanently ended.",
      "They expected uncontrolled enthusiasm to give way to disappointment and a chain of declining support.",
    ],
    answer: 3,
    explanation:
      "두 연구자는 1980년대의 열광이 통제를 벗어났으며 실망이 뒤따를 것이라고 경고했습니다. 이어 연구계와 언론의 비관, 지원 축소로 이어지는 연쇄 반응을 설명합니다.",
    difficulty: 2,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-053",
    topic: "ai",
    passageId: "winter-cycles",
    prompt: "Which two periods are identified as the major AI winters?",
    options: [
      "1974–1980 and 1987–2000.",
      "1974–1980 and 1988–2000.",
      "1971–1975 and 1987–2000.",
      "1987–2000 and the renewed-interest period beginning in 2012.",
    ],
    answer: 0,
    explanation: "주요 두 겨울은 약 1974~1980년과 1987~2000년으로 제시됩니다.",
    difficulty: 1,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-054",
    topic: "ai",
    passageId: "winter-cycles",
    prompt: "Which event appears in the list of smaller episodes?",
    options: [
      "1966: criticism of perceptrons.",
      "1966: failure of machine translation.",
      "1973: failure of machine translation.",
      "1987: cancellation of new spending on AI.",
    ],
    answer: 1,
    explanation:
      "작은 에피소드 목록에 1966년 기계번역 실패가 포함되어 있습니다.",
    difficulty: 1,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-055",
    topic: "ai",
    passageId: "winter-cycles",
    prompt:
      "What trend does the passage describe after AI’s low point in the early 1990s?",
    options: [
      "Enthusiasm increased, but optimism declined after the early-1990s low point.",
      "Interest rose only among corporate communities, not researchers.",
      "Enthusiasm and optimism generally increased.",
      "Interest remained at its early-1990s low point.",
    ],
    answer: 2,
    explanation:
      "1990년대 초 저점 이후 AI에 대한 열정과 낙관이 전반적으로 증가했다고 합니다.",
    difficulty: 2,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-056",
    topic: "ai",
    passageId: "winter-cycles",
    prompt:
      "What does the range of events in the AI-winter list suggest about those periods?",
    options: [
      "They consisted only of commercial product failures, not decisions by funding agencies.",
      "Every episode concerned criticism of a single neural-network architecture.",
      "Funding cutbacks began only after the LISP machine market collapsed.",
      "They involved technical disappointments, market changes, and funding decisions rather than one kind of setback.",
    ],
    answer: 3,
    explanation:
      "목록에는 기계 번역의 실패와 퍼셉트론 비판뿐 아니라 LISP 시장 붕괴, 연구비 축소와 신규 지출 취소도 포함됩니다. 따라서 한 종류의 사건으로만 이루어진 시기가 아닙니다.",
    difficulty: 2,
    source: {
      title: "AI winter",
      url: "https://en.wikipedia.org/wiki/AI_winter",
      revisionId: 1374895630,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1374895630",
      revisionTimestamp: "2026-09-14T18:20:45Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-057",
    topic: "ai",
    passageId: "expert-overview",
    prompt: "What is an expert system designed to emulate?",
    options: [
      "The decision-making ability of a human expert.",
      "The decision-making ability of a machine-learning model.",
      "The fact-and-rule storage function of a knowledge base only.",
      "The linguistic behavior of a human expert without decision-making.",
    ],
    answer: 0,
    explanation:
      "전문가 시스템은 인간 전문가의 의사결정 능력을 모방하는 컴퓨터 시스템입니다.",
    difficulty: 1,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-058",
    topic: "ai",
    passageId: "expert-overview",
    prompt: "How are expert systems’ bodies of knowledge mainly represented?",
    options: [
      "Facts and rules represented in conventional procedural code.",
      "As if–then rules rather than conventional procedural code.",
      "If–then rules without a body of knowledge containing facts.",
      "Numerical weights rather than explicit rules.",
    ],
    answer: 1,
    explanation:
      "지식은 전통적 절차형 코드보다 주로 if–then 규칙으로 표현됩니다.",
    difficulty: 2,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-059",
    topic: "ai",
    passageId: "expert-overview",
    prompt: "When were expert systems created and when did they proliferate?",
    options: [
      "Created in the 1970s and proliferated in the 1990s.",
      "Created in the 1980s and proliferated in the 1970s.",
      "Created in the 1970s and proliferated in the 1980s.",
      "Created in the 1970s and proliferated only after neural networks succeeded.",
    ],
    answer: 2,
    explanation:
      "지문은 1970년대에 만들어져 1980년대에 널리 퍼졌다고 설명합니다.",
    difficulty: 1,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-060",
    topic: "ai",
    passageId: "expert-overview",
    prompt:
      "Why were expert systems widely regarded as the future of AI at one point?",
    options: [
      "They were widely admired in the 1980s but had not yet achieved practical success.",
      "They were among the first successful forms of AI, but only after neural networks succeeded.",
      "They were regarded as the future because they used successful artificial neural networks.",
      "They were among the first truly successful AI software before successful artificial neural networks.",
    ],
    answer: 3,
    explanation:
      "성공적인 인공 신경망이 등장하기 전에 최초의 진정한 성공 AI 소프트웨어 중 하나였기 때문입니다.",
    difficulty: 3,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-061",
    topic: "ai",
    passageId: "expert-subsystems",
    prompt: "What are the two subsystems of an expert system?",
    options: [
      "A knowledge base and an inference engine.",
      "A knowledge base and a neural network.",
      "An inference engine and a transcript evaluator.",
      "A rule base and a conventional procedural program.",
    ],
    answer: 0,
    explanation:
      "지문은 지식 기반과 추론 엔진이라는 두 하위 시스템으로 나눕니다.",
    difficulty: 1,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-062",
    topic: "ai",
    passageId: "expert-subsystems",
    prompt: "What does the knowledge base represent?",
    options: [
      "Facts and rules together with every fact later deduced by the engine.",
      "Facts and rules.",
      "Known facts only, while rules belong exclusively to the inference engine.",
      "If–then rules without any represented facts.",
    ],
    answer: 1,
    explanation: "knowledge base는 사실과 규칙을 나타냅니다.",
    difficulty: 1,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-063",
    topic: "ai",
    passageId: "expert-subsystems",
    prompt: "What does the inference engine do with known facts?",
    options: [
      "It stores facts and rules for later use.",
      "It applies rules to classify images but cannot deduce new facts.",
      "It applies rules to the known facts to deduce new facts.",
      "It uses known facts to delete the rules that matched them.",
    ],
    answer: 2,
    explanation:
      "추론 엔진은 알려진 사실에 규칙을 적용해 새로운 사실을 추론합니다.",
    difficulty: 2,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-064",
    topic: "ai",
    passageId: "expert-subsystems",
    prompt: "Which contrast best captures the roles of the two subsystems?",
    options: [
      "The knowledge base applies rules, while the inference engine stores facts.",
      "The knowledge base stores facts only, while the engine explains but cannot apply rules.",
      "Both subsystems independently store the same facts and rules.",
      "The knowledge base stores represented facts and rules, while the inference engine applies them and may explain or debug.",
    ],
    answer: 3,
    explanation:
      "지식 기반은 사실·규칙을 저장하고 추론 엔진은 이를 적용하며 설명·디버깅도 할 수 있습니다.",
    difficulty: 3,
    source: {
      title: "Expert system",
      url: "https://en.wikipedia.org/wiki/Expert_system",
      revisionId: 1376006928,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376006928",
      revisionTimestamp: "2026-09-21T12:32:00Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-065",
    topic: "ai",
    passageId: "llm-overview",
    prompt: "What is a large language model trained on?",
    options: [
      "A vast amount of text for natural language processing tasks.",
      "A vast amount of text primarily for image-classification tasks.",
      "A curated set of if–then rules for natural-language generation.",
      "A vast amount of text only after the model has been fine-tuned.",
    ],
    answer: 0,
    explanation:
      "LLM은 자연어 처리, 특히 언어 생성을 위해 방대한 텍스트로 훈련됩니다.",
    difficulty: 1,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-066",
    topic: "ai",
    passageId: "llm-overview",
    prompt:
      "Which set of activities does the passage say LLMs can typically perform?",
    options: [
      "Generate, summarize, translate, and analyze images.",
      "Generate, summarize, translate, and analyze text.",
      "Generate and summarize text, but not translate or analyze it.",
      "Analyze text only after fine-tuning the model as an assistant.",
    ],
    answer: 1,
    explanation:
      "생성·요약·번역·텍스트 분석이 전형적인 LLM 기능으로 열거됩니다.",
    difficulty: 1,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-067",
    topic: "ai",
    passageId: "llm-overview",
    prompt: "What does a GPT pre-trained model learn to predict?",
    options: [
      "The next sentence only.",
      "The next chatbot response after instruction fine-tuning.",
      "The next word.",
      "The next word during inference, but not during pre-training.",
    ],
    answer: 2,
    explanation: "GPT는 다음 단어를 예측하도록 사전 훈련됩니다.",
    difficulty: 1,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-068",
    topic: "ai",
    passageId: "llm-overview",
    prompt:
      "Which summary correctly connects GPTs, LLMs, and chatbots as described here?",
    options: [
      "Every LLM is a GPT, and the two labels refer to exactly the same model family.",
      "Chatbots are the architecture on which transformer models are generally based.",
      "GPTs are a separate model family that does not belong to the LLM category.",
      "GPTs are one type of LLM, while LLMs generally use transformers and underlie many chatbots.",
    ],
    answer: 3,
    explanation:
      "지문은 GPT를 LLM의 한 종류라고 소개하고, LLM은 보통 트랜스포머 구조에 기반하며 여러 챗봇의 토대가 된다고 설명합니다. 서로 다른 범주의 관계를 바꾸거나 전부 동일시하면 안 됩니다.",
    difficulty: 2,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-069",
    topic: "ai",
    passageId: "llm-limitations",
    prompt: "What architecture are LLMs typically based on?",
    options: [
      "Transformer architecture.",
      "A recurrent neural-network architecture.",
      "A Monte Carlo tree-search architecture.",
      "An expert-system architecture based on if–then rules.",
    ],
    answer: 0,
    explanation:
      "지문은 LLM이 일반적으로 transformer architecture에 기반한다고 말합니다.",
    difficulty: 1,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-070",
    topic: "ai",
    passageId: "llm-limitations",
    prompt: "What can biased or inaccurate training data do to an LLM?",
    options: [
      "Guarantee reliable output when the training data are biased.",
      "Make its output less reliable.",
      "Make benchmark evaluations unnecessary.",
      "Reduce reliability only when the model generates images.",
    ],
    answer: 1,
    explanation:
      "편향되거나 부정확한 학습 데이터는 출력의 신뢰성을 낮출 수 있습니다.",
    difficulty: 2,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-071",
    topic: "ai",
    passageId: "llm-limitations",
    prompt: "Which qualities do benchmark evaluations attempt to measure?",
    options: [
      "Reasoning, factual accuracy, and alignment, but not safety.",
      "Factual accuracy and safety only.",
      "Reasoning, factual accuracy, alignment, and safety.",
      "Reasoning and model size rather than alignment.",
    ],
    answer: 2,
    explanation: "벤치마크는 추론·사실 정확성·정렬·안전을 측정하려고 합니다.",
    difficulty: 2,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-072",
    topic: "ai",
    passageId: "llm-limitations",
    prompt:
      "Which statement correctly connects the passage’s GPT and LLM descriptions?",
    options: [
      "GPTs are LLMs, but their training-data quality cannot affect reliability.",
      "GPTs are not LLMs, although both use transformer architecture.",
      "LLMs use transformers, but GPTs predict the next word only after fine-tuning.",
      "GPTs are a type of LLM, and their data quality can affect reliability.",
    ],
    answer: 3,
    explanation:
      "GPT는 LLM의 한 종류이고 편향되거나 부정확한 데이터는 LLM 출력의 신뢰성에 영향을 줍니다.",
    difficulty: 3,
    source: {
      title: "Large language model",
      url: "https://en.wikipedia.org/wiki/Large_language_model",
      revisionId: 1376616067,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1376616067",
      revisionTimestamp: "2026-09-25T05:43:16Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-073",
    topic: "ai",
    passageId: "vision-overview",
    prompt: "What do computer vision tasks include?",
    options: [
      "Acquiring, processing, analyzing, and understanding digital images.",
      "Acquiring and processing digital images, but not analyzing or understanding them.",
      "Analyzing high-dimensional data only after converting it into text.",
      "Understanding visual images without acquiring or processing them.",
    ],
    answer: 0,
    explanation:
      "컴퓨터 비전의 작업에는 디지털 이미지의 획득·처리·분석·이해가 포함됩니다.",
    difficulty: 1,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-074",
    topic: "ai",
    passageId: "vision-overview",
    prompt:
      "What does “understanding” signify in this computer-vision context?",
    options: [
      "Transforming visual images into descriptions that cannot guide action.",
      "Transforming visual images into descriptions of the world that can elicit appropriate action.",
      "Using geometric models to replace descriptions of the world.",
      "Producing numerical decisions without first forming descriptions of the world.",
    ],
    answer: 1,
    explanation:
      "이해는 시각 이미지를 세계를 설명하는 정보로 바꾸어 적절한 행동을 이끌 수 있게 하는 것입니다.",
    difficulty: 2,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-075",
    topic: "ai",
    passageId: "vision-overview",
    prompt:
      "Which fields help construct models for disentangling symbolic information from image data?",
    options: [
      "Geometry, physics, and statistics, but not learning theory.",
      "Geometry, learning theory, and linguistics, but not physics.",
      "Geometry, physics, statistics, and learning theory.",
      "Physics, statistics, and computer science only.",
    ],
    answer: 2,
    explanation:
      "지문은 기하학·물리학·통계학·학습 이론을 모델 구성에 활용한다고 열거합니다.",
    difficulty: 2,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-076",
    topic: "ai",
    passageId: "vision-overview",
    prompt:
      "What kind of output can computer vision produce from high-dimensional real-world data?",
    options: [
      "Numerical information but not symbolic information.",
      "Symbolic descriptions but not decisions.",
      "Decisions only, without numerical information.",
      "Numerical or symbolic information, such as decisions.",
    ],
    answer: 3,
    explanation:
      "현실의 고차원 데이터에서 수치 또는 결정과 같은 기호 정보를 산출할 수 있다고 합니다.",
    difficulty: 3,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-077",
    topic: "ai",
    passageId: "vision-disciplines",
    prompt:
      "How does the passage distinguish the scientific discipline of computer vision?",
    options: [
      "It concerns the theory behind artificial systems that extract information from images.",
      "It concerns the theory behind natural-language systems that extract information from text.",
      "It concerns construction of camera hardware rather than theory.",
      "It concerns artificial systems that generate images rather than extract information from them.",
    ],
    answer: 0,
    explanation:
      "과학 분야로서 컴퓨터 비전은 이미지에서 정보를 추출하는 인공 시스템의 이론을 다룹니다.",
    difficulty: 2,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-078",
    topic: "ai",
    passageId: "vision-disciplines",
    prompt: "Which form of image data is explicitly mentioned?",
    options: [
      "Video sequences and single-camera views from a 3D scanner.",
      "Video sequences, views from multiple cameras, or 3D scanner data.",
      "Views from multiple cameras and audio recordings.",
      "3D point clouds only from medical scanning devices.",
    ],
    answer: 1,
    explanation:
      "영상 시퀀스, 여러 카메라 시점, 3D 스캐너 데이터가 이미지 데이터의 예로 제시됩니다.",
    difficulty: 1,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-079",
    topic: "ai",
    passageId: "vision-disciplines",
    prompt:
      "Which item belongs to the listed subdisciplines of computer vision?",
    options: [
      "Image classification.",
      "Image captioning.",
      "Object detection.",
      "Object generation.",
    ],
    answer: 2,
    explanation: "object detection은 컴퓨터 비전 하위 분야 목록에 포함됩니다.",
    difficulty: 1,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
  {
    id: "dad-ai-080",
    topic: "ai",
    passageId: "vision-disciplines",
    prompt: "What does the technological discipline seek to do?",
    options: [
      "Apply theories and models to analyze images without constructing systems.",
      "Construct systems first and develop theories only afterward.",
      "Apply theories to extract information but not to build systems.",
      "Apply theories and models to construct computer-vision systems.",
    ],
    answer: 3,
    explanation:
      "기술 분야는 이론과 모델을 적용해 컴퓨터 비전 시스템을 구축하려고 합니다.",
    difficulty: 2,
    source: {
      title: "Computer vision",
      url: "https://en.wikipedia.org/wiki/Computer_vision",
      revisionId: 1372994537,
      revisionUrl: "https://en.wikipedia.org/w/index.php?oldid=1372994537",
      revisionTimestamp: "2026-09-03T11:34:52Z",
      retrievedAt: "2026-09-26T11:51:12Z",
      attribution: "Wikipedia contributors",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
  },
];

const attachPassage = (question) => {
  const passage = passageById.get(question.passageId);
  if (!passage) throw new Error(`Missing AI passage: ${question.passageId}`);
  return Object.freeze({ ...question, passage: passage.text });
};

export const dadAIQuestions = Object.freeze(questionSpecs.map(attachPassage));
export const DAD_AI_ARTICLE_COUNT = articleById.size;
export const DAD_AI_PASSAGE_COUNT = passageById.size;
