const SOURCE_URL = "https://namu.wiki/w/위저딩%20월드/마법%20물건";

const canonicalSpecs = [
  {
    id: "item-wand",
    name: "마법 지팡이",
    model: "wand",
    color: "#6b4423",
    accent: "#d3a253",
    description: "마법사들이 마법을 부릴 때 사용하는 도구다.",
  },
  {
    id: "item-broom",
    name: "빗자루",
    model: "broom",
    color: "#704626",
    accent: "#d8aa4b",
    description: "마법사 사회에서 비행과 이동에 쓰이는 마법 빗자루다.",
  },
  {
    id: "item-cauldron",
    name: "솥단지",
    model: "cauldron",
    color: "#34383d",
    accent: "#bb7a3c",
    description: "마법약을 만들 때 쓰는 금속 솥단지로 여러 재질과 크기가 있다.",
  },
  {
    id: "item-speaking-mirror",
    name: "말하는 거울",
    model: "mirror",
    color: "#73818e",
    accent: "#d4b56e",
    description: "사용자에게 말을 걸고 몸가짐을 조언하는 마법 거울이다.",
  },
  {
    id: "item-erised-mirror",
    name: "소망의 거울",
    model: "mirror",
    color: "#30283f",
    accent: "#d8b86a",
    description: "보는 이가 가장 간절히 바라는 모습을 비추는 거울이다.",
  },
  {
    id: "item-two-way-mirror",
    name: "양면 거울",
    model: "mirror",
    color: "#273949",
    accent: "#78b6ca",
    description: "떨어진 두 사람이 서로의 모습을 볼 수 있게 하는 거울이다.",
  },
  {
    id: "item-foe-glass",
    name: "적을 비추는 거울",
    model: "mirror",
    color: "#3e4954",
    accent: "#ba4e58",
    description: "적이 가까워질수록 흐릿한 형체가 선명해지는 거울이다.",
  },
  {
    id: "item-wizard-chess",
    name: "마법사 체스세트",
    model: "chess",
    color: "#d9d1c5",
    accent: "#252932",
    description: "말들이 살아 움직이며 지시에 따라 싸우는 체스세트다.",
  },
  {
    id: "item-gobstones",
    name: "곱스톤",
    model: "orb",
    color: "#b99758",
    accent: "#5a80a6",
    description:
      "패배자에게 끈끈하고 냄새 나는 점액을 쏘는 마법 구슬 게임이다.",
  },
  {
    id: "item-exploding-snap",
    name: "폭탄 카드",
    model: "gadget",
    color: "#a13e35",
    accent: "#edbd58",
    description: "보통 카드처럼 보이지만 갑자기 폭발하는 마법 카드다.",
  },
  {
    id: "item-everlasting-flame-branch",
    name: "구브라이시안 불의 가지",
    model: "lantern",
    color: "#573823",
    accent: "#f2a63b",
    description: "덤블도어가 마법을 걸어 영원히 타오르게 한 나뭇가지다.",
  },
  {
    id: "item-gryffindor-sword",
    name: "그리핀도르의 검",
    model: "sword",
    color: "#7f2430",
    accent: "#d8b957",
    description: "고블린이 만든 그리핀도르 가문의 전설적인 검이다.",
  },
  {
    id: "item-portrait",
    name: "그림",
    model: "camera",
    color: "#4f3024",
    accent: "#d4a254",
    description:
      "마법이 걸린 초상화 속 인물은 움직이고 말하며 액자 사이를 오간다.",
  },
  {
    id: "item-quick-quotes-quill",
    name: "속기 깃펜",
    model: "quill",
    color: "#2d2322",
    accent: "#d07a45",
    description:
      "인터뷰 내용을 받아 적는 대신 사용자의 의도대로 기사를 꾸며 쓰는 깃펜이다.",
  },
  {
    id: "item-umberidge-quill",
    name: "덜로리스 엄브리지의 깃펜",
    model: "quill",
    color: "#482631",
    accent: "#e1a1a1",
    description:
      "글을 쓰는 이의 피를 잉크로 삼아 손등에 문장을 새기는 깃펜이다.",
  },
  {
    id: "item-weasley-quill",
    name: "위즐리 쌍둥이의 깃펜",
    model: "quill",
    color: "#4b265b",
    accent: "#f0ad3d",
    description:
      "잘못 쓴 글자와 오답을 자동으로 고치지만 시간이 지나면 오작동하는 깃펜이다.",
  },
  {
    id: "item-acceptance-quill-book",
    name: "입학 승인 깃펜과 입학 허가 책",
    model: "book",
    color: "#1f252e",
    accent: "#bfc4cc",
    description:
      "마법적 재능을 감지한 아이의 이름을 기록해 호그와트 입학을 결정하는 책과 깃펜이다.",
  },
  {
    id: "item-thieves-map",
    name: "도둑 지도",
    model: "scroll",
    color: "#c8b58e",
    accent: "#6b3f2a",
    description: "호그와트의 통로와 사람들의 위치를 마법으로 보여 주는 지도다.",
  },
  {
    id: "item-deluminator",
    name: "딜루미네이터",
    model: "gadget",
    color: "#3d4148",
    accent: "#90b7c6",
    description: "빛을 껐다가 저장하고 되돌리는 작은 마법 장치다.",
  },
  {
    id: "item-radio",
    name: "라디오",
    model: "radio",
    color: "#3a2f28",
    accent: "#c58a43",
    description: "마법사 사회에서 방송을 듣는 데 널리 쓰이는 라디오다.",
  },
  {
    id: "item-rememberall",
    name: "리멤브럴",
    model: "orb",
    color: "#e6e5dd",
    accent: "#c53e3e",
    description: "잊은 일이 있을 때 안개가 빨갛게 변하는 유리공이다.",
  },
  {
    id: "item-philosophers-stone",
    name: "마법사의 돌",
    model: "orb",
    color: "#9e2528",
    accent: "#f0d067",
    description: "불로장생의 영약을 만들고 금속을 금으로 바꾸는 전설의 돌이다.",
  },
  {
    id: "item-spello-tape",
    name: "마법 테이프",
    model: "ribbon",
    color: "#6f89aa",
    accent: "#c9d8e6",
    description: "망가진 지팡이나 물건을 임시로 붙이는 마법 테이프다.",
  },
  {
    id: "item-sorting-hat",
    name: "기숙사 배정 모자",
    model: "hat",
    color: "#493329",
    accent: "#bd8a45",
    description: "호그와트 신입생의 성향을 읽어 기숙사를 정해 주는 모자다.",
  },
  {
    id: "item-fire-goblet",
    name: "불의 잔",
    model: "goblet",
    color: "#27333a",
    accent: "#e08b35",
    description: "트라이위저드 시합의 챔피언을 선택하는 마법의 잔이다.",
  },
  {
    id: "item-secrecy-detector",
    name: "비밀 탐지기",
    model: "gadget",
    color: "#c99a35",
    accent: "#f0d66b",
    description: "비밀이나 거짓말이 감지되면 작동하는 황금 안테나 모양 장치다.",
  },
  {
    id: "item-vanishing-cabinet",
    name: "사라지는 캐비닛",
    model: "cabinet",
    color: "#3f302b",
    accent: "#b58855",
    description:
      "한 쌍이 연결되어 사람과 물건을 서로 다른 장소로 옮기는 캐비닛이다.",
  },
  {
    id: "item-golden-watch",
    name: "금시계",
    model: "clock",
    color: "#b38127",
    accent: "#f4d477",
    description:
      "열두 개의 바늘 대신 시계 가장자리를 도는 행성이 표시된 금시계다.",
  },
  {
    id: "item-time-turner",
    name: "타임 터너(시간을 거꾸로 돌리는 시계)",
    model: "clock",
    color: "#c39a36",
    accent: "#8cd0d1",
    description: "시계를 돌려 시간을 되돌리는 목걸이형 마법 물건이다.",
  },
  {
    id: "item-weasley-clock",
    name: "9개의 황금색 바늘만 있는 괘종시계",
    model: "clock",
    color: "#845c24",
    accent: "#e1b849",
    description:
      "위즐리 가족 구성원의 상태와 위치를 아홉 개의 바늘로 알려 주는 시계다.",
  },
  {
    id: "item-slughorn-hourglass",
    name: "호러스 슬러그혼 교수의 모래시계",
    model: "clock",
    color: "#473c56",
    accent: "#d5ab5b",
    description: "대화의 흥미에 따라 모래가 흐르는 속도가 달라지는 모래시계다.",
  },
  {
    id: "item-sirius-knife",
    name: "시리우스의 주머니칼",
    model: "knife",
    color: "#34383e",
    accent: "#b8c4cd",
    description:
      "틈에 밀어 넣어 어떠한 자물쇠라도 열 수 있는 마법 주머니칼이다.",
  },
  {
    id: "item-sneakoscope",
    name: "스니코스코프",
    model: "orb",
    color: "#59646e",
    accent: "#d7bc5b",
    description: "믿지 못할 사람이 주변에 있으면 빛을 내며 도는 유리 팽이다.",
  },
  {
    id: "item-skower-cleaner",
    name: "스코워 부인의 다목적 마법 세정제",
    model: "bottle",
    color: "#416c55",
    accent: "#d7e8ba",
    description: "마법사의 세계에서 청소에 사용하는 다목적 세정제다.",
  },
  {
    id: "item-hand-of-glory",
    name: "영광의 손",
    model: "lantern",
    color: "#805c43",
    accent: "#efb94a",
    description: "초를 끼우면 손을 든 사람에게만 빛을 비추는 손 모양 등불이다.",
  },
  {
    id: "item-omnioculars",
    name: "옴니큘러스",
    model: "camera",
    color: "#9a7740",
    accent: "#d5c177",
    description:
      "지난 장면을 재생하고 느리게 보며 경기 장면을 편집하는 황동 관측 장치다.",
  },
  {
    id: "item-flying-carpet",
    name: "양탄자",
    model: "carpet",
    color: "#6b2f45",
    accent: "#d4a849",
    description:
      "빗자루처럼 날 수 있는 마법 양탄자로 영국에서는 사용이 금지되어 있다.",
  },
  {
    id: "item-magical-camera",
    name: "카메라",
    model: "camera",
    color: "#34383b",
    accent: "#9b6f42",
    description:
      "플래시를 터뜨리면 보랏빛 연기가 피어오르는 마법사들의 카메라다.",
  },
  {
    id: "item-golden-snitch",
    name: "골든 스니치",
    sourceName: "퀴디치의 공들",
    model: "snitch",
    color: "#bd8b25",
    accent: "#f6d56b",
    description: "퀴디치에서 빠르게 날아다니는 날개 달린 작은 공이다.",
  },
  {
    id: "item-quaffle",
    name: "퀘이플",
    sourceName: "퀴디치의 공들",
    model: "quaffle",
    color: "#8b2e2a",
    accent: "#d56c4a",
    description: "퀴디치 경기에서 선수들이 주고받는 큰 붉은 공이다.",
  },
  {
    id: "item-bludger",
    name: "블러저",
    sourceName: "퀴디치의 공들",
    model: "bludger",
    color: "#3b3f46",
    accent: "#a6adb6",
    description: "퀴디치 경기에서 선수들을 향해 날아드는 무거운 공이다.",
  },
  {
    id: "item-christmas-cracker",
    name: "크리스마스 크래커",
    model: "envelope",
    color: "#9c2f3b",
    accent: "#e6c45b",
    description:
      "마법사 연회에서 터뜨리면 모자와 장난감 같은 물건이 나오는 폭죽이다.",
  },
  {
    id: "item-tent",
    name: "텐트",
    model: "tent",
    color: "#536e54",
    accent: "#d4ad67",
    description: "확장 마법으로 욕실과 주방과 방까지 품는 마법 텐트다.",
  },
  {
    id: "item-seven-lock-trunk",
    name: "자물쇠가 7개 달린 트렁크",
    model: "trunk",
    color: "#4b352b",
    accent: "#ba873e",
    description: "자물쇠를 열 때마다 별도의 공간이 나타나는 확장형 트렁크다.",
  },
  {
    id: "item-pensieve",
    name: "펜시브",
    model: "pensieve",
    color: "#66727b",
    accent: "#d1bb72",
    description: "기억을 꺼내 담고 들여다볼 수 있는 마법의 돌그릇이다.",
  },
  {
    id: "item-portkey",
    name: "포트키",
    model: "gadget",
    color: "#61452f",
    accent: "#b99758",
    description: "정해진 때에 접촉하면 지정된 장소로 순간이동시키는 물건이다.",
  },
  {
    id: "item-revealer",
    name: "폭로개",
    model: "gadget",
    color: "#b9383b",
    accent: "#f0a159",
    description:
      "지워진 글자가 있는 종이를 문지르면 글자를 드러내는 빨간 도구다.",
  },
  {
    id: "item-floo-powder",
    name: "플루 가루",
    model: "bottle",
    color: "#3f5d63",
    accent: "#a8d1c7",
    description:
      "벽난로 네트워크를 통해 마법사 사회를 오가는 데 쓰이는 가루다.",
  },
  {
    id: "item-howler",
    name: "하울러",
    model: "envelope",
    color: "#a22c2e",
    accent: "#e56e3f",
    description:
      "붉은 편지봉투에서 보낸 사람의 증폭된 성난 목소리가 터져 나오는 물건이다.",
  },
  {
    id: "item-magical-firework",
    name: "마법의 불꽃놀이 폭죽",
    model: "orb",
    color: "#3e386d",
    accent: "#e58b43",
    description: "터지면 특수한 불꽃과 소동을 일으키는 마법 폭죽이다.",
  },
  {
    id: "item-dungbomb",
    name: "똥폭탄",
    model: "orb",
    color: "#4b392d",
    accent: "#a27a44",
    description: "터지면 지독한 냄새를 퍼뜨리는 장난용 마법 물건이다.",
  },
  {
    id: "item-decoy-detonator",
    name: "미끼 나팔",
    model: "gadget",
    color: "#343b40",
    accent: "#e2aa4e",
    description:
      "움직이기 시작하면 앞이 보이지 않을 정도의 연기를 내뿜는 장난감이다.",
  },
  {
    id: "item-fake-wand",
    name: "가짜 지팡이",
    model: "wand",
    color: "#8b3b2c",
    accent: "#e0b34f",
    description:
      "마법을 시도하는 순간 고무 장난감 등으로 변하는 위즐리 형제의 장난감이다.",
  },
  {
    id: "item-fanged-frisbee",
    name: "송곳니 원반",
    model: "gadget",
    color: "#4a3e33",
    accent: "#c5d0d0",
    description: "스스로 날아다니며 주위 사람을 이빨로 괴롭히는 원반이다.",
  },
  {
    id: "item-deathly-hallows",
    name: "죽음의 성물",
    model: "gadget",
    color: "#222a34",
    accent: "#cbb166",
    description:
      "딱총나무 지팡이, 부활의 돌, 투명 망토를 묶어 부르는 이름이다.",
  },
];

const variantStyles = [
  {
    label: "청동 세공",
    detail: "홈이 파인 황동 고리와 손잡이",
    use: "교실 실습대에 놓기 좋은 형태",
    variant: "ornate",
    color: "#704a2f",
    accent: "#c9944a",
  },
  {
    label: "서리빛 마감",
    detail: "반투명 유리판과 서리 낀 가장자리",
    use: "병동과 세탁실에서 쉽게 식별되는 형태",
    variant: "slender",
    color: "#566777",
    accent: "#b9d7df",
  },
  {
    label: "자주빛 광택",
    detail: "겹친 자주색 판과 넓은 받침",
    use: "연회장 장식과 전시를 위한 형태",
    variant: "wide",
    color: "#543e67",
    accent: "#d08bb0",
  },
  {
    label: "별무늬 장식",
    detail: "금빛 별을 새긴 테두리와 이중 테두리",
    use: "탑과 기숙사에서 눈에 띄는 표식용 형태",
    variant: "ornate",
    color: "#273955",
    accent: "#d9b85b",
  },
  {
    label: "호박 유약",
    detail: "두꺼운 호박 유약과 길어진 목 부분",
    use: "주방과 약품 선반에서 내용물을 보호하는 형태",
    variant: "tall",
    color: "#765034",
    accent: "#e0a648",
  },
  {
    label: "청록 테두리",
    detail: "물결 모양 청록 테두리와 가는 몸체",
    use: "욕실과 호숫가의 습한 환경에 맞춘 형태",
    variant: "slender",
    color: "#285d5c",
    accent: "#9bd0c2",
  },
  {
    label: "흑요석 결",
    detail: "매끈한 흑요석 판과 무거운 바닥 링",
    use: "비밀 통로와 지하실에 두는 견고한 형태",
    variant: "wide",
    color: "#272c35",
    accent: "#8997aa",
  },
  {
    label: "은빛 세공",
    detail: "은실 격자와 탈착식 작은 고리",
    use: "도서관과 사무실에서 기록을 정리하는 형태",
    variant: "ornate",
    color: "#69747d",
    accent: "#dae0dd",
  },
  {
    label: "루비 테두리",
    detail: "붉은 보석 못과 튼튼한 가죽 끈",
    use: "그리핀도르 전시와 의식에 맞춘 형태",
    variant: "tall",
    color: "#642d36",
    accent: "#e2955b",
  },
  {
    label: "비취 광택",
    detail: "비취색 격자와 잎맥 모양의 홈",
    use: "온실과 정원에서 식물을 다루는 형태",
    variant: "ornate",
    color: "#2c6654",
    accent: "#b8d76d",
  },
  {
    label: "밤하늘 무늬",
    detail: "작은 별자리 점과 회전하는 원판",
    use: "천문탑에서 관측을 돕는 형태",
    variant: "wide",
    color: "#252b48",
    accent: "#9ba8e0",
  },
  {
    label: "참나무 결",
    detail: "거친 참나무 판과 굵은 황동 경첩",
    use: "숲과 야외 캠프에서 휴대하는 형태",
    variant: "tall",
    color: "#60402e",
    accent: "#b77c48",
  },
];

const canonicalById = new Map(canonicalSpecs.map((spec) => [spec.id, spec]));

function makeFacilityVariant({
  id,
  name,
  variantOf,
  model,
  color,
  accent,
  variant = "ornate",
  description,
}) {
  const base = canonicalById.get(variantOf);
  if (!base) throw new Error(`Unknown canonical base ${variantOf}`);
  return {
    id,
    name,
    model,
    color,
    accent,
    variant,
    sourceName: base.sourceName ?? base.name,
    sourceUrl: SOURCE_URL,
    canon: false,
    variantOf,
    description: `${description} ${base.name}를 바탕으로 한 게임용 변형이며 원전의 고유 물건을 새로 주장하지 않는다.`,
  };
}

const facilityVariants = [
  makeFacilityVariant({
    id: "item-greenhouse-grow-cauldron",
    name: "재배솥",
    variantOf: "item-cauldron",
    model: "cauldron",
    color: "#345444",
    accent: "#b6d77a",
    variant: "wide",
    description: "온실 재배대 사이에 놓고 흙과 마법 비료를 섞는 넓은 솥이다.",
  }),
  makeFacilityVariant({
    id: "item-greenhouse-record-quill",
    name: "식물관리기록깃펜",
    variantOf: "item-quick-quotes-quill",
    model: "quill",
    color: "#315b46",
    accent: "#d6b85d",
    variant: "slender",
    description: "잎의 상태와 물주기 기록을 양피지에 남기는 가는 깃펜이다.",
  }),
  makeFacilityVariant({
    id: "item-greenhouse-herbarium-book",
    name: "약초자료 기록책",
    variantOf: "item-acceptance-quill-book",
    model: "book",
    color: "#354e38",
    accent: "#c4a866",
    variant: "wide",
    description: "약초 도감과 씨앗 표본을 펼쳐 두는 온실용 참고책이다.",
  }),
  makeFacilityVariant({
    id: "item-greenhouse-seed-trunk",
    name: "씨앗 보관 트렁크",
    variantOf: "item-seven-lock-trunk",
    model: "trunk",
    color: "#5a432c",
    accent: "#b9a05c",
    variant: "tall",
    description: "습기를 막는 작은 칸에 씨앗 봉투와 구근을 나누어 보관한다.",
  }),
  makeFacilityVariant({
    id: "item-greenhouse-cleaner",
    name: "온실용 마법 세정제",
    variantOf: "item-skower-cleaner",
    model: "bottle",
    color: "#3d714c",
    accent: "#c2e394",
    variant: "slender",
    description: "유리 온실 창과 분무관의 흙 얼룩을 닦는 식물 친화적 세정제다.",
  }),
  makeFacilityVariant({
    id: "item-greenhouse-observation-orb",
    name: "유리 식물관찰구",
    variantOf: "item-rememberall",
    model: "orb",
    color: "#b8d7c2",
    accent: "#6aa768",
    variant: "wide",
    description:
      "잎의 시듦과 마법 반응을 안개 색으로 보여 주는 거품 유리 구슬이다.",
  }),
  makeFacilityVariant({
    id: "item-greenhouse-specimen-camera",
    name: "식물표본 카메라",
    variantOf: "item-magical-camera",
    model: "camera",
    color: "#3c5542",
    accent: "#d1b15b",
    variant: "ornate",
    description: "움직이는 잎과 꽃의 성장 단계를 기록하는 온실용 카메라다.",
  }),
  makeFacilityVariant({
    id: "item-greenhouse-watering-wand",
    name: "분무 관리 지팡이",
    variantOf: "item-wand",
    model: "wand",
    color: "#3a6b4c",
    accent: "#9ed2ae",
    variant: "slender",
    description: "재배대 위에 고른 물안개를 뿌리는 온실 관리용 지팡이다.",
  }),
  makeFacilityVariant({
    id: "item-kitchen-cook-cauldron",
    name: "자동젓기 조리솥",
    variantOf: "item-cauldron",
    model: "cauldron",
    color: "#6b3d28",
    accent: "#db9a47",
    variant: "wide",
    description:
      "주방 화덕 위에서 국물과 소스를 스스로 저어 주는 조리용 솥이다.",
  }),
  makeFacilityVariant({
    id: "item-kitchen-recipe-quill",
    name: "주방 조리기록 깃펜",
    variantOf: "item-quick-quotes-quill",
    model: "quill",
    color: "#4d3327",
    accent: "#e0b35b",
    variant: "ornate",
    description: "대형 식탁의 주문과 조리법을 빠르게 적는 주방용 깃펜이다.",
  }),
  makeFacilityVariant({
    id: "item-kitchen-spice-trunk",
    name: "향신료 저장 트렁크",
    variantOf: "item-seven-lock-trunk",
    model: "trunk",
    color: "#71422d",
    accent: "#d89b45",
    variant: "tall",
    description:
      "향신료와 밀가루 봉투를 냄새 섞임 없이 나누는 작은 저장 트렁크다.",
  }),
  makeFacilityVariant({
    id: "item-kitchen-cleaner",
    name: "주방용 마법 세정제",
    variantOf: "item-skower-cleaner",
    model: "bottle",
    color: "#704227",
    accent: "#d5bd75",
    variant: "slender",
    description: "구리 솥과 은식기의 기름때를 빠르게 없애는 주방 세정제다.",
  }),
  makeFacilityVariant({
    id: "item-potions-ingredient-bottle",
    name: "약초 재료 보관병",
    variantOf: "item-skower-cleaner",
    model: "bottle",
    color: "#35576a",
    accent: "#a8d5df",
    variant: "wide",
    description:
      "마법약 교실에서 말린 약초와 액체 재료를 분리해 두는 눈금 병이다.",
  }),
  makeFacilityVariant({
    id: "item-laundry-record-quill",
    name: "세탁기록 깃펜",
    variantOf: "item-quick-quotes-quill",
    model: "quill",
    color: "#38596b",
    accent: "#d2e4e9",
    variant: "slender",
    description: "세탁물 주인과 건조 순서를 기록하는 세탁실 깃펜이다.",
  }),
  makeFacilityVariant({
    id: "item-laundry-linen-trunk",
    name: "린넨 보관 트렁크",
    variantOf: "item-seven-lock-trunk",
    model: "trunk",
    color: "#536875",
    accent: "#d8e4da",
    variant: "tall",
    description: "접은 수건과 망토를 습기에서 지키는 세탁실 보관 트렁크다.",
  }),
  makeFacilityVariant({
    id: "item-laundry-cleaner",
    name: "세탁용 마법 세정제",
    variantOf: "item-skower-cleaner",
    model: "bottle",
    color: "#49778d",
    accent: "#c6e6ef",
    variant: "slender",
    description: "비눗방울과 얼룩을 분해해 흰 천을 보존하는 세탁용 세정제다.",
  }),
  makeFacilityVariant({
    id: "item-potions-brewing-cauldron",
    name: "수업용 약솥",
    variantOf: "item-cauldron",
    model: "cauldron",
    color: "#3e334e",
    accent: "#b971ca",
    variant: "tall",
    description: "마법약 교실의 학생 실습대에 맞춘 눈금 있는 약제용 솥이다.",
  }),
  makeFacilityVariant({
    id: "item-potions-label-quill",
    name: "약병 라벨 깃펜",
    variantOf: "item-quick-quotes-quill",
    model: "quill",
    color: "#4a3157",
    accent: "#d9a5df",
    variant: "slender",
    description:
      "약초와 위험한 약액의 이름을 작은 라벨에 적는 수업용 깃펜이다.",
  }),
  makeFacilityVariant({
    id: "item-hospital-remedy-bottle",
    name: "회복약 보관병",
    variantOf: "item-skower-cleaner",
    model: "bottle",
    color: "#819c78",
    accent: "#e2d38b",
    variant: "tall",
    description: "병동 약품장에 회복 물약을 나누어 보관하는 눈금 병이다.",
  }),
  makeFacilityVariant({
    id: "item-hospital-chart-quill",
    name: "병동 차트 깃펜",
    variantOf: "item-quick-quotes-quill",
    model: "quill",
    color: "#6d7e75",
    accent: "#e1c982",
    variant: "slender",
    description: "환자의 상태와 투약 시간을 침상별 차트에 기록하는 깃펜이다.",
  }),
  makeFacilityVariant({
    id: "item-hospital-supply-trunk",
    name: "치료도구 트렁크",
    variantOf: "item-seven-lock-trunk",
    model: "trunk",
    color: "#57625e",
    accent: "#d2b86e",
    variant: "wide",
    description: "붕대와 약숟가락을 칸별로 정리해 두는 병동용 트렁크다.",
  }),
  makeFacilityVariant({
    id: "item-hospital-memory-orb",
    name: "환자 관찰 구슬",
    variantOf: "item-rememberall",
    model: "orb",
    color: "#d9e4d2",
    accent: "#b87569",
    variant: "slender",
    description: "환자의 맥박 변화를 색 안개로 알려 주는 병동 관찰용 유리구다.",
  }),
  makeFacilityVariant({
    id: "item-library-catalog-quill",
    name: "도서관 목록 깃펜",
    variantOf: "item-quick-quotes-quill",
    model: "quill",
    color: "#5e4935",
    accent: "#d8bf7b",
    variant: "slender",
    description: "책 제목과 서가 위치를 목록 카드에 정리하는 사서용 깃펜이다.",
  }),
  makeFacilityVariant({
    id: "item-library-rare-book",
    name: "금서 보관 책",
    variantOf: "item-acceptance-quill-book",
    model: "book",
    color: "#302d32",
    accent: "#aa8d58",
    variant: "tall",
    description:
      "도서관 제한 서가에 봉인된 마법 지식을 보관하는 전시용 책이다.",
  }),
  makeFacilityVariant({
    id: "item-library-archive-trunk",
    name: "자료보관 트렁크",
    variantOf: "item-seven-lock-trunk",
    model: "trunk",
    color: "#54483c",
    accent: "#c4a869",
    variant: "wide",
    description:
      "양피지와 지도 묶음을 먼지 없이 보존하는 도서관 자료 트렁크다.",
  }),
  makeFacilityVariant({
    id: "item-library-reading-mirror",
    name: "열람용 말하는 거울",
    variantOf: "item-speaking-mirror",
    model: "mirror",
    color: "#635a50",
    accent: "#d9c58e",
    variant: "ornate",
    description:
      "서가의 책 위치와 조용한 열람 규칙을 알려 주는 도서관 거울이다.",
  }),
  makeFacilityVariant({
    id: "item-bathhouse-mirror",
    name: "목욕실 말하는 거울",
    variantOf: "item-speaking-mirror",
    model: "mirror",
    color: "#477486",
    accent: "#c6ecdf",
    variant: "wide",
    description: "반장 욕실에서 물 온도와 비누 위치를 알려 주는 장식 거울이다.",
  }),
  makeFacilityVariant({
    id: "item-bathhouse-timer",
    name: "목욕 시간 시계",
    variantOf: "item-golden-watch",
    model: "clock",
    color: "#47717a",
    accent: "#e2c66d",
    variant: "ornate",
    description: "욕조의 온도와 목욕 시간을 알려 주는 반장 욕실 시계다.",
  }),
  makeFacilityVariant({
    id: "item-bathhouse-cleaner",
    name: "욕실용 마법 세정제",
    variantOf: "item-skower-cleaner",
    model: "bottle",
    color: "#3c7782",
    accent: "#c6eee1",
    variant: "slender",
    description: "대리석 욕조와 푸른 타일의 물때를 지우는 욕실 세정제다.",
  }),
  makeFacilityVariant({
    id: "item-forest-camp-lantern",
    name: "숲길 휴대 불씨등",
    variantOf: "item-everlasting-flame-branch",
    model: "lantern",
    color: "#513b2a",
    accent: "#e7a33c",
    variant: "tall",
    description:
      "야영지에서 꺼지지 않는 작은 불씨를 감싸 들고 다니는 휴대 등불이다.",
  }),
];

const magicalItems = [
  ...canonicalSpecs.map((spec) => ({
    id: spec.id,
    name: spec.name,
    model: spec.model,
    color: spec.color,
    accent: spec.accent,
    variant: "plain",
    sourceName: spec.sourceName ?? spec.name,
    sourceUrl: SOURCE_URL,
    canon: true,
    variantOf: null,
    description: spec.description,
  })),
  ...canonicalSpecs.map((spec, index) => {
    const style = variantStyles[index % variantStyles.length];
    return {
      id: `${spec.id}-variant`,
      name: `${spec.name} ${style.label}`,
      model: spec.model,
      color: style.color,
      accent: style.accent,
      variant: style.variant,
      sourceName: spec.sourceName ?? spec.name,
      sourceUrl: SOURCE_URL,
      canon: false,
      variantOf: spec.id,
      description: `${spec.sourceName ?? spec.name}를 바탕으로 한 게임용 변형이다. ${style.detail}을 더해 ${style.use}로 설계했으며 원전의 고유 물건을 새로 주장하지 않는다.`,
    };
  }),
  ...facilityVariants,
];

const pair = (id) => [id, `${id}-variant`];

const facilityItemIds = {
  "facility-01": [
    ...pair("item-wand"),
    ...pair("item-portrait"),
    ...pair("item-quick-quotes-quill"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-two-way-mirror"),
    ...pair("item-radio"),
    ...pair("item-acceptance-quill-book"),
    "item-gobstones",
  ],
  "facility-02": [
    ...pair("item-wand"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-golden-watch"),
    ...pair("item-speaking-mirror"),
    ...pair("item-radio"),
    ...pair("item-portrait"),
    "item-gobstones",
  ],
  "facility-03": [
    ...pair("item-wand"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-golden-watch"),
    ...pair("item-two-way-mirror"),
    ...pair("item-thieves-map"),
    ...pair("item-radio"),
    "item-sneakoscope",
  ],
  "facility-04": [
    ...pair("item-wand"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-golden-watch"),
    ...pair("item-speaking-mirror"),
    ...pair("item-fake-wand"),
    ...pair("item-quick-quotes-quill"),
    "item-gobstones",
  ],
  "facility-05": [
    "item-cauldron",
    "item-kitchen-cook-cauldron",
    "item-quick-quotes-quill",
    "item-kitchen-recipe-quill",
    "item-seven-lock-trunk",
    "item-kitchen-spice-trunk",
    "item-skower-cleaner",
    "item-kitchen-cleaner",
    "item-radio",
    "item-radio-variant",
    "item-acceptance-quill-book",
    "item-acceptance-quill-book-variant",
    "item-skower-cleaner-variant",
    "item-quick-quotes-quill-variant",
    "item-cauldron-variant",
  ],
  "facility-06": [
    "item-quick-quotes-quill",
    "item-laundry-record-quill",
    "item-quick-quotes-quill-variant",
    "item-seven-lock-trunk",
    "item-laundry-linen-trunk",
    "item-seven-lock-trunk-variant",
    "item-skower-cleaner",
    "item-laundry-cleaner",
    "item-skower-cleaner-variant",
    "item-spello-tape",
    "item-spello-tape-variant",
    "item-radio",
    "item-radio-variant",
    "item-rememberall",
    "item-rememberall-variant",
  ],
  "facility-07": [
    "item-cauldron",
    "item-potions-brewing-cauldron",
    "item-cauldron-variant",
    "item-quick-quotes-quill",
    "item-potions-label-quill",
    "item-quick-quotes-quill-variant",
    "item-wand",
    "item-wand-variant",
    "item-acceptance-quill-book",
    "item-acceptance-quill-book-variant",
    "item-rememberall",
    "item-rememberall-variant",
    "item-sneakoscope",
    "item-sneakoscope-variant",
    "item-potions-ingredient-bottle",
  ],
  "facility-08": [
    ...pair("item-fire-goblet"),
    ...pair("item-flying-carpet"),
    ...pair("item-portrait"),
    ...pair("item-speaking-mirror"),
    ...pair("item-radio"),
    ...pair("item-golden-watch"),
    ...pair("item-quick-quotes-quill"),
    "item-howler",
  ],
  "facility-09": [
    ...pair("item-wizard-chess"),
    ...pair("item-wand"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-flying-carpet"),
    ...pair("item-thieves-map"),
    ...pair("item-speaking-mirror"),
    ...pair("item-gobstones"),
    "item-philosophers-stone",
  ],
  "facility-10": [
    ...pair("item-speaking-mirror"),
    ...pair("item-two-way-mirror"),
    ...pair("item-foe-glass"),
    ...pair("item-vanishing-cabinet"),
    ...pair("item-wand"),
    ...pair("item-portkey"),
    ...pair("item-floo-powder"),
    "item-sneakoscope",
  ],
  "facility-11": [
    ...pair("item-flying-carpet"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-tent"),
    ...pair("item-portkey"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-radio"),
    ...pair("item-speaking-mirror"),
    "item-golden-watch",
  ],
  "facility-12": [
    ...pair("item-portrait"),
    ...pair("item-vanishing-cabinet"),
    ...pair("item-golden-watch"),
    ...pair("item-flying-carpet"),
    ...pair("item-speaking-mirror"),
    ...pair("item-quick-quotes-quill"),
    ...pair("item-thieves-map"),
    "item-deluminator",
  ],
  "facility-13": [
    ...pair("item-sorting-hat"),
    ...pair("item-fire-goblet"),
    ...pair("item-portrait"),
    ...pair("item-flying-carpet"),
    ...pair("item-golden-watch"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-quick-quotes-quill"),
    "item-howler",
  ],
  "facility-14": [
    ...pair("item-flying-carpet"),
    ...pair("item-tent"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-portkey"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-broom"),
    ...pair("item-radio"),
    "item-golden-watch",
  ],
  "facility-15": [
    ...pair("item-thieves-map"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-quick-quotes-quill"),
    ...pair("item-portrait"),
    ...pair("item-vanishing-cabinet"),
    ...pair("item-golden-watch"),
    ...pair("item-radio"),
    "item-wand",
  ],
  "facility-16": [
    ...pair("item-radio"),
    ...pair("item-magical-camera"),
    ...pair("item-golden-watch"),
    ...pair("item-portrait"),
    ...pair("item-speaking-mirror"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-quick-quotes-quill"),
    "item-omnioculars",
  ],
  "facility-17": [
    ...pair("item-wand"),
    ...pair("item-fake-wand"),
    ...pair("item-foe-glass"),
    ...pair("item-sneakoscope"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-golden-watch"),
    ...pair("item-wizard-chess"),
    "item-deluminator",
  ],
  "facility-18": [
    ...pair("item-wand"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-quick-quotes-quill"),
    ...pair("item-golden-watch"),
    ...pair("item-portrait"),
    ...pair("item-vanishing-cabinet"),
    ...pair("item-speaking-mirror"),
    "item-deluminator",
  ],
  "facility-19": [
    ...pair("item-speaking-mirror"),
    ...pair("item-two-way-mirror"),
    ...pair("item-revealer"),
    ...pair("item-golden-watch"),
    ...pair("item-floo-powder"),
    ...pair("item-portkey"),
    ...pair("item-spello-tape"),
    "item-sneakoscope",
  ],
  "facility-20": [
    "item-hospital-remedy-bottle",
    "item-hospital-chart-quill",
    "item-hospital-supply-trunk",
    "item-hospital-memory-orb",
    "item-skower-cleaner",
    "item-skower-cleaner-variant",
    "item-tent",
    "item-tent-variant",
    "item-seven-lock-trunk",
    "item-seven-lock-trunk-variant",
    "item-golden-watch",
    "item-golden-watch-variant",
    "item-speaking-mirror",
    "item-speaking-mirror-variant",
    "item-radio",
  ],
  "facility-21": [
    ...pair("item-wand"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-quick-quotes-quill"),
    ...pair("item-thieves-map"),
    ...pair("item-rememberall"),
    ...pair("item-sneakoscope"),
    ...pair("item-golden-watch"),
    "item-deluminator",
  ],
  "facility-22": [
    ...pair("item-fire-goblet"),
    ...pair("item-flying-carpet"),
    ...pair("item-portrait"),
    ...pair("item-golden-watch"),
    ...pair("item-vanishing-cabinet"),
    ...pair("item-speaking-mirror"),
    ...pair("item-deluminator"),
    "item-wand",
  ],
  "facility-23": [
    ...pair("item-gryffindor-sword"),
    ...pair("item-portrait"),
    ...pair("item-vanishing-cabinet"),
    ...pair("item-speaking-mirror"),
    ...pair("item-golden-watch"),
    ...pair("item-broom"),
    ...pair("item-flying-carpet"),
    "item-wand",
  ],
  "facility-24": [
    ...pair("item-erised-mirror"),
    ...pair("item-speaking-mirror"),
    ...pair("item-two-way-mirror"),
    ...pair("item-flying-carpet"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-golden-watch"),
    ...pair("item-portrait"),
    "item-rememberall",
  ],
  "facility-25": [
    "item-library-catalog-quill",
    "item-library-rare-book",
    "item-library-archive-trunk",
    "item-library-reading-mirror",
    "item-thieves-map",
    "item-thieves-map-variant",
    "item-acceptance-quill-book",
    "item-acceptance-quill-book-variant",
    "item-quick-quotes-quill",
    "item-quick-quotes-quill-variant",
    "item-portrait",
    "item-portrait-variant",
    "item-golden-watch",
    "item-golden-watch-variant",
    "item-vanishing-cabinet",
  ],
  "facility-26": [
    "item-bathhouse-mirror",
    "item-bathhouse-timer",
    "item-bathhouse-cleaner",
    "item-speaking-mirror",
    "item-speaking-mirror-variant",
    "item-two-way-mirror",
    "item-two-way-mirror-variant",
    "item-golden-watch",
    "item-golden-watch-variant",
    "item-skower-cleaner",
    "item-skower-cleaner-variant",
    "item-rememberall",
    "item-rememberall-variant",
    "item-seven-lock-trunk",
    "item-seven-lock-trunk-variant",
  ],
  "facility-27": [
    ...pair("item-wand"),
    ...pair("item-fake-wand"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-quick-quotes-quill"),
    ...pair("item-wizard-chess"),
    ...pair("item-speaking-mirror"),
    ...pair("item-golden-watch"),
    "item-deluminator",
  ],
  "facility-28": [
    ...pair("item-vanishing-cabinet"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-tent"),
    ...pair("item-flying-carpet"),
    ...pair("item-wizard-chess"),
    ...pair("item-speaking-mirror"),
    ...pair("item-wand"),
    "item-portkey",
  ],
  "facility-29": [
    ...pair("item-omnioculars"),
    ...pair("item-golden-watch"),
    ...pair("item-rememberall"),
    ...pair("item-sneakoscope"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-portkey"),
    ...pair("item-magical-camera"),
    "item-wand",
  ],
  "facility-30": [
    ...pair("item-tent"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-golden-watch"),
    ...pair("item-radio"),
    ...pair("item-speaking-mirror"),
    ...pair("item-portkey"),
    "item-flying-carpet",
  ],
  "facility-31": [
    ...pair("item-omnioculars"),
    ...pair("item-golden-watch"),
    ...pair("item-rememberall"),
    ...pair("item-thieves-map"),
    ...pair("item-radio"),
    ...pair("item-everlasting-flame-branch"),
    ...pair("item-speaking-mirror"),
    "item-sneakoscope",
  ],
  "facility-32": [
    ...pair("item-pensieve"),
    ...pair("item-sorting-hat"),
    ...pair("item-deluminator"),
    ...pair("item-portrait"),
    ...pair("item-acceptance-quill-book"),
    ...pair("item-golden-watch"),
    ...pair("item-vanishing-cabinet"),
    "item-omnioculars",
  ],
  "facility-33": [
    "item-tent",
    "item-tent-variant",
    "item-flying-carpet",
    "item-flying-carpet-variant",
    "item-portkey",
    "item-portkey-variant",
    "item-everlasting-flame-branch",
    "item-everlasting-flame-branch-variant",
    "item-seven-lock-trunk",
    "item-seven-lock-trunk-variant",
    "item-radio",
    "item-radio-variant",
    "item-floo-powder",
    "item-floo-powder-variant",
    "item-forest-camp-lantern",
  ],
  "facility-34": [
    ...pair("item-broom"),
    ...pair("item-flying-carpet"),
    ...pair("item-portkey"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-radio"),
    ...pair("item-golden-watch"),
    ...pair("item-speaking-mirror"),
    "item-wand",
  ],
  "facility-35": [
    "item-cauldron",
    "item-greenhouse-grow-cauldron",
    "item-quick-quotes-quill",
    "item-greenhouse-record-quill",
    "item-acceptance-quill-book",
    "item-greenhouse-herbarium-book",
    "item-seven-lock-trunk",
    "item-greenhouse-seed-trunk",
    "item-skower-cleaner",
    "item-greenhouse-cleaner",
    "item-rememberall",
    "item-greenhouse-observation-orb",
    "item-magical-camera",
    "item-greenhouse-specimen-camera",
    "item-greenhouse-watering-wand",
  ],
  "facility-36": [
    ...pair("item-broom"),
    ...pair("item-golden-snitch"),
    ...pair("item-quaffle"),
    ...pair("item-bludger"),
    ...pair("item-omnioculars"),
    ...pair("item-magical-camera"),
    ...pair("item-tent"),
    "item-seven-lock-trunk",
  ],
  "facility-37": [
    ...pair("item-tent"),
    ...pair("item-flying-carpet"),
    ...pair("item-portkey"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-radio"),
    ...pair("item-speaking-mirror"),
    ...pair("item-golden-watch"),
    "item-everlasting-flame-branch",
  ],
  "facility-38": [
    ...pair("item-seven-lock-trunk"),
    ...pair("item-tent"),
    ...pair("item-radio"),
    ...pair("item-wand"),
    ...pair("item-sirius-knife"),
    ...pair("item-floo-powder"),
    ...pair("item-flying-carpet"),
    "item-skower-cleaner",
  ],
  "facility-39": [
    ...pair("item-broom"),
    ...pair("item-golden-snitch"),
    ...pair("item-quaffle"),
    ...pair("item-bludger"),
    ...pair("item-seven-lock-trunk"),
    ...pair("item-vanishing-cabinet"),
    ...pair("item-flying-carpet"),
    "item-omnioculars",
  ],
  "facility-40": [
    ...pair("item-broom"),
    ...pair("item-golden-snitch"),
    ...pair("item-quaffle"),
    ...pair("item-bludger"),
    ...pair("item-flying-carpet"),
    ...pair("item-tent"),
    ...pair("item-portkey"),
    "item-radio",
  ],
};

const itemsById = new Map(magicalItems.map((item) => [item.id, item]));

export { magicalItems, facilityItemIds };

export function itemsForRoom(room) {
  const facilityId =
    typeof room === "string" ? room : (room?.facilityId ?? room?.id);
  const ids = facilityItemIds[facilityId];
  if (!ids) {
    throw new Error(
      `Unknown Hogwarts facility: ${facilityId ?? "(missing id)"}`,
    );
  }
  return ids.map((id) => {
    const item = itemsById.get(id);
    if (!item) {
      throw new Error(`Unknown magical item ${id} in ${facilityId}`);
    }
    return item;
  });
}
